name: Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Build with Make
      run: make
      
    - name: Test basic functionality
      run: |
        echo "Hello, world" | ./BeaudyShell
        
    - name: Build with CMake
      run: |
        mkdir -p build
        cd build
        cmake ..
        cmake --build .
        
    - name: Run static analysis
      run: |
        sudo apt-get install -y cppcheck
        cppcheck --enable=all --suppress=missingIncludeSystem .